https://powcoder.com
代写代考加微信 powcoder
Assignment Project Exam Help
Add WeChat powcoder
(* DO NOT EDIT THIS FILE *)

module type T = sig
  val day_of_week : int -> int -> int -> int
  val sigma : (int -> int) -> int -> int -> int
  val pi : (int -> int) -> int -> int -> int
  val reduce : 
    ('a -> 'a) -> ('a -> bool) -> ('b -> 'c -> 'c) -> 'c -> 
    ('a -> 'b) -> 'a -> 'c
  val sigma_r : (int -> int) -> int -> int -> int
  val pi_r : (int -> int) -> int -> int -> int
  val reduce_tr : 
    ('a -> 'a) -> ('a -> bool) -> ('b -> 'c -> 'c) -> 'c -> 
    ('a -> 'b) -> 'a -> 'c  
  val sigma_tr : (int -> int) -> int -> int -> int
  val pi_tr : (int -> int) -> int -> int -> int
  val partition : int list -> int list * int list
  val multi_partition : int -> int list -> int list list
end

module M : T = Warmup
